# Change these first
owner: jogerj # Your GitHub username
repo: ap-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Mail
    url: $MAIL_URL
  - name: Mail Admin
    url: $MAIL_ADMIN_URL
  - name: APAJ Website
    url: $AP_1
  - name: APKP Website
    url: $AP_2
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /ap-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /ap-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
